use mavenmovies;

1) Retrieve the total number of rentals made in the Sakila database;
select count(rental_id) as total_rentals from rental;


2) Find the average rental duration (in days) of movies rented from the Sakila database;
select avg(datediff(return_date, rental_date)) rental_duration_in_days from rental;
select avg(rental_duration) as rental_duration_in_days from film;


3)Display the first name and last name of customers in uppercase;
select upper(first_name) as fa, upper(last_name) as la from customer;


4) Extract the month from the rental date and display it alongside the rental ID;
select rental_id, month(rental_date) as rental_month from rental;
 
5)Retrieve the count of rentals for each customer (display customer ID and the count of rentals);
select customer_id, count(rental_id) as count_of_rentals from rental
group by customer_id;

6)Find the total revenue generated by each store;
select s.store_id, sum(p.amount) as tot_revenue from store s
inner join staff st on s.store_id = st.store_id
inner join payment p on p.staff_id = st.staff_id
group by store_id;


7) Display the title of the movie, customer first name, and last name who rented it;
select f.title as movie_title, c.first_name, c.last_name from film f
inner join inventory i on i.film_id = f.film_id
inner join rental r on r.inventory_id = i.inventory_id
inner join customer c on c.customer_id = r. customer_id;


8) Retrieve the names of all actors who have appeared in the film "Gone with the Wind.";
select a.first_name, a.last_name from actor a
inner join film_actor fa on fa.actor_id = a.actor_id
inner join film f on f.film_id = fa.film_id
where f.title = 'Gone with the wind';

9) Determine the total number of rentals for each category of movies;

select fc.category_id, count(r.rental_id) as rental_count from rental r
inner join inventory i on i.inventory_id = r.inventory_id
inner join film f on f.film_id = i.film_id
inner join film_category fc on fc.film_id = f.film_id
group by fc.category_id;

10) Find the average rental rate of movies in each language;
select l.name as language, avg(f.rental_rate) as a_rntl_rte from film f
inner join language l on l.language_id = f.language_id
group by l.name;

11) Retrieve the customer names along with the total amount they have spent on rentals;
select c.first_name, c.last_name, sum(p.amount) as tot_amnt from customer c
inner join payment p on p.customer_id = c.customer_id
inner join rental r on r.customer_id = p.customer_id
group by c.customer_id;


12) List the titles of movies rented by each customer in a particular city (e.g., 'London');
select c.first_name, c.last_name, f.title as rented_movietitle from customer c
inner join address a on a.address_id = c.address_id
inner join city ct on ct.city_id = a.city_id
inner join rental r on c.customer_id = r.customer_id
inner join inventory i on i.inventory_id = r.inventory_id
inner join film f on f.film_id = i.film_id
where ct.city = 'London'
group by c.first_name, c.last_name, f.title;



13) Display the top 5 rented movies along with the number of times they be have ben rented;

select f.title as movie_title, count(rental_id) as rental_num from film f
inner join inventory i on f.film_id = i.film_id
join rental r on r.inventory_id = i.inventory_id
group by f.title 
order by rental_num desc
limit 5;

select f.title, count(*) from rental r
join inventory i on i.inventory_id =r.inventory_id
join film f on f.film_id = i.film_id
group by f.title
order by count(*) desc
limit 5;


14) Determine the customers who have rented movies from both stores (store ID 1 and store ID 2);
select c.customer_id, c.first_name, c.last_name from customer c
 join rental r on r.customer_id = c.customer_id
 join inventory i on i.inventory_id = r.inventory_id
 join store s on s.store_id = i.store_id
 where s.store_id in (1,2)
 group by c.customer_id, c.first_name, c.last_name
 having count(distinct s.store_id) =2;